### ISSUE TITLE
VLAN in CLI appears to be wrong for BCF

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/poseidon#1034]

**Comment by gregs5** [comment]
What Poseidon seems to be displaying under the VLAN field currently is what BCF actually refers to as a "tenant." BCF uses "tenants" and "segments."  My guess is that we want the segment name or description as the VLAN.  Name would probably be best, albeit in our internal environment we put the VLAN # in the description.  But we are weirdos, and that's probably not what others do; I'd stick with segment name.
