### ISSUE TITLE
investigate what's needed to fix the log parser for Faucet

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/poseidon#1314]

**Comment by anarkiwi** [comment]
What we could do, is create a new optional log on the FAUCET side that just logs the events that the notifier sends.
That way you could specify a file path and read that and use the exact same parser as you do with events received from RBQ.

**Comment by cglewis** [comment]
ohh. that would be nice actually. i've always thought the log parsing was a brittle approach since it's a format that the Poseidon side can't control. but if it was the same what the notifier sends, then it can at least be evaluated into an object and interrogated safely.

**Comment by cglewis** [comment]
I propose faucetagent would be a replacement for this need.
