### ISSUE TITLE
Query about using the Jupyter Notebooks

### ISSUE THREAD

**Issue by rayush7** [CyberReboot/poseidon#221]
Hi @bradh41 

I read your post [here.](https://blog.cyberreboot.org/deep-session-learning-for-cyber-security-e7c0f6804b81) Being a newbie to the world of Machine Learning based Cyber Security, I found it very informative. Thank you for that.

I found so many Jupyter Notebooks in the repo. Which one should I start with? Also how can I collect the raw hex dump of the headers (any tool which can help me) for my own custom use case? 

Thank you

**Comment by d-grossman** [comment]
Use  [tcpdump](http://www.tcpdump.org/tcpdump_man.html)  to capture then take a look at [utils.py](https://github.com/CyberReboot/poseidon/blob/multi-docker/notebooks/advesarial/utils.py)

As far as which notebook to begin with the ones in [traditional ml](https://github.com/CyberReboot/poseidon/tree/multi-docker/notebooks/traditional_ml) then move to the deep learning ones as you feel more comfortable..

**Comment by rayush7** [comment]
Thanks @d-grossman. That was helpful.
