### ISSUE TITLE
Test creation: firstrun

### ISSUE THREAD

**Issue by d-grossman** [CyberReboot/poseidon#230]
NorthboundControllerAbstraction needs better coverage for testing.

add testing for  **first_run** to **test_NorthBoundControllerAbstraction.py**

**Comment by pradyunsg** [comment]
I would be interested in taking this on (along with the entire bundle of other ones).

**Comment by cglewis** [comment]
Go for it 👍

**Comment by d-grossman** [comment]
@pradyunsg, are you still working on this? If Not I'll take it over.

**Comment by pradyunsg** [comment]
@d-grossman Thanks for asking!

Feel free to. :)
