### ISSUE TITLE
Test creation: print_endpoint_state

### ISSUE THREAD

**Issue by d-grossman** [CyberReboot/poseidon#240]
NorthboundControllerAbstraction needs better coverage for testing.

add testing for **print_endpoint_state** to **test_NorthBoundControllerAbstraction.py**

**Comment by jbenjos** [comment]
I'll take this one.

**Comment by d-grossman** [comment]
@jbenjos you have 1 more day to produce on this one before I free it up for someone else.

**Comment by jbenjos** [comment]
I'm not really sure what to test on this one. It doesn't seem to return anything and the only side effect appears to be calls to the logger. Just test the function and ensure it returns no exception?

**Comment by jbenjos** [comment]
#313
