### ISSUE TITLE
send metadata to endprocess via Vent

### ISSUE THREAD

**Issue by d-grossman** [CyberReboot/poseidon#258]
The machine learning process benefits from knowing some metadata about the data it is processing.

poseidonMonitor::start_vent_collector()
should add a **'metadata'** field to the **'payload'** dict.
**'metadata'** should be assigned the connection metadata associated with the **dev_hash** key passed into the function. get the metadata from **uss.return_endpoint_state()**

**Comment by sanchezg** [comment]
Hi! Can I take this?

**Comment by d-grossman** [comment]
@sanchezg Boom, it is yours!

**Comment by sanchezg** [comment]
@d-grossman Thanks!

Also, I would like to recommend you the use of `json.dumps` instead of casting to `str`, for example in the involved method:
```
    def start_vent_collector(self, dev_hash, num_captures=1):
        '''
        ...
        '''
        try:
            # ...
            self.logger.debug('vent payload: ' + str(payload))
```

I see that is only a log message, but in the future can be useful to you use some parser to debug/show/view those messages.
