### ISSUE TITLE
config file ocd

### ISSUE THREAD

**Issue by d-grossman** [CyberReboot/poseidon#259]
everything but two entries uses _ for separating works... make the config uniform.

`rabbit-server` = RABBIT_SERVER
`rabbit-port` = RABBIT_PORT

change to:

**`rabbit_server`** = RABBIT_SERVER
**`rabbit_port`** = RABBIT_PORT

fix code to look for the _ versions..

**Comment by ben-e-whitney** [comment]
I would like to do this. Should the modified code still accept `rabbit-server` and `rabbit-port` for backwards compatibility?

**Comment by d-grossman** [comment]
backwards compatibility not needed. 

Thanks for your interest!
