### ISSUE TITLE
helperFunctions Mixed with my classes: poseidonMonitor

### ISSUE THREAD

**Issue by d-grossman** [CyberReboot/poseidon#262]
Some of the functions within **poseidonMonitor** can be moved into a **poseidonMonitor_helper.py** file

1. create the poseidonMonitor_helper.py file in the same directory as poseidonMonitor.py  
2. add the appropriate headers to the top of the file  
3. move the helper functions into the new file  
4. add the imports, call the functions correctly now that they are in a new location  
5. put what functions were moved into the issue so I can update the Testing issues.

**Comment by matheus-manoel** [comment]
Will look into that in October :D. Are all the functions outside the class considered helper functions?

**Comment by d-grossman** [comment]
yes.
