### ISSUE TITLE
Endpoint class creation

### ISSUE THREAD

**Issue by d-grossman** [CyberReboot/poseidon#263]
Create an Endpoint.py in the same dir as poseidonMonitor.py
stores information like:
```javascript
{
'tenant': u'FLOORPLATE', 
'mac': u'de:ad:be:ef:7f:12', 
'segment': u'prod', 
'name': None, 
'ip-address': u'102.179.20.100'
}
```

the class should have member variables
state(str) - current state the endpoint is in
next-state(str) - the next state for the endpoint
data(dict) - for storing the above example info

the class should have the following member functions
init by dictionary to make a new object . 
make_hash (see NorthboundControllerAbstraction::make_hash)
to_str - make string representation of internals of object
to_json - should return a json view of the object
from_json -initialize object from json
update_state - state <- next_state, next_state <- 'NONE' or a string that is passed as a parameter.

**Comment by Jorissss** [comment]
I can look at this. What is meant by the 'state' the endpoint is in?
