### ISSUE TITLE
Make a docker container to build docs

### ISSUE THREAD

**Issue by d-grossman** [CyberReboot/poseidon#279]
1. create a dockerfile called Dockerfile.docs (you may want to look at the pre-existing container)
1. Sphinx the project (see http://docs.readthedocs.io/en/latest/getting_started.html)
1. have output placed somewhere under docs

building the container should look like:
docker build -f ./Dockerfile.docs -t poseidon.docs .

running the container should look like:
docker run -v/`someDir`:`/pathTo/docs` poseidon.docs

`someDir` - would be where to write updated version of docs
`/pathTo/docs` - inside the container where things are being written

If you have questions please ask. (use the existing Dockerfile as a reference)

**Comment by viveksyngh** [comment]
I have added Dockerfile. Can you tell me from which directory of repo docs will be build ?

**Comment by viveksyngh** [comment]
There is already a conf.py present in /docs folder.. should I override the existing conf.py file ?

**Comment by d-grossman** [comment]
please overwrite the existing docs/conf.py file
