### ISSUE TITLE
moving on up to python3 to a new deluxe set of problems in the sky...

### ISSUE THREAD

**Issue by d-grossman** [CyberReboot/poseidon#289]
move the codebase to python3

1. upgrade Dockerfile(s)
1. update requirements.txt file
1. update packages
1. remove python27 isms
1. add python3 isms
1. get testing working
1. upgrade circleci to build with python3 container

**Comment by aeroaks** [comment]
I would like to give it a try! but might need your guidance!

**Comment by d-grossman** [comment]
@aeroaks, I'm sorry I already assigned to myself.
