### ISSUE TITLE
config files referenced out of /tmp

### ISSUE THREAD

**Issue by d-grossman** [CyberReboot/poseidon#296]
Currently to make things work with circleci automated build process a config file is referenced out of /tmp/.  The annoyance was duplicated into the docker builds so the project could move on.  This should be changed for running out of our docker containers.

see: ```poseidon/poseidonMonitor/Config/Config.py```
```config_template_path = '/tmp/poseidonWork/config/poseidon.config'```

1. make an environment variable so circleci pulls from ```/tmp```
1. update the docker container to not ```RUN ln -s /poseidonWork /tmp/poseidonWork```

1. test to make sure everything is happy running out of ```/poseidonWork``` in the container
1. propagate changes to ```Dockerfile.docs```

**Comment by danielpops** [comment]
I'd like to take a look
