### ISSUE TITLE
get metrics out of the controller for bytes sent/received on a port

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/poseidon#353]
An attached SDN switch will have statistics like how many bytes were sent and received on a given port, SDN controllers can usually get this information and often have APIs for northbound applications (such as Poseidon) to retrieve such information.  This issue would be figuring out the available API calls from the controller (currently only BCF) to get this information into Poseidon.

**Comment by matan7890** [comment]
Hey, can you explain a little more what does it mean? Add a little description to the task?
Thanks!

**Comment by cglewis** [comment]
@matan7890 updated - let me know if that helps.
