### ISSUE TITLE
Makefile 'awk' error on macOS (messes up TAG variable)

### ISSUE THREAD

**Issue by 1uka** [CyberReboot/poseidon#366]
In more detail, invoking `who | awk '{print $$1}` on macOS 10.13 returns the whole column, when it should return only the first item from the first column. This causes the TAG variable to contain 3 times the username (`whoami`), and then it also causes all the docker commands to fail.

Steps to reproduce (on macOS):

1. cd poseidon
2. make build_poseidon

Further down is the output of both the `make` and `awk` errors. I have a fix for the issue and I am making a PR just after i have opened this issue. I hope i can be of help

Output of `make build_poseidon`:
```
docker build -f ./Dockerfile.poseidon -t luka luka luka-poseidon .
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
make: *** [build_poseidon] Error 1
```

Output of `who | awk '{print $$1}'`
```
awk: illegal field $(luka), name "1"
 input record number 1, file
 source line number 1
```

**Comment by d-grossman** [comment]
@1uka please verify that this still works on a linux system/ linux vm. Then I'll approve the pull.

**Comment by 1uka** [comment]
Verified on:

1. Ubuntu 10.04 LTS
2. Ubuntu 17.04 LTS
3. Debian 9

I tested both `sh` and `bash` , works on both shells, and will work on others, too.
