### ISSUE TITLE
interface-group

### ISSUE THREAD

**Issue by d-grossman** [CyberReboot/poseidon#399]
make the destination interface group name *ig1*  configurable.

```
! interface-group
interface-group ig1
  description 'packets get mirrored here to be processed'
  mode span-fabric
  member switch YOUR_LEAF_SWITCH interface YOUR_INTERFACE_WHERE_VENT_WILL_RECORD_TRAFFIC_FROM
```

./poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/bcf.py:            "dest-interface-group": "ig1",
./poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/sample_state.py:    "dest-interface-group": "ig1",

**Comment by rashley-iqt** [comment]
I'm going to treat this similarly to the span-fabric option added in #400

**Comment by cglewis** [comment]
do you want to open a PR for #400 first and get that merged before starting on this one?
