### ISSUE TITLE
span_fabric name

### ISSUE THREAD

**Issue by d-grossman** [CyberReboot/poseidon#400]
make the span_fabric name configurable.  *vent* needs to be configurable..

```
! span-fabric
span-fabric *vent*
  active
  destination interface-group ig1
  priority 1
```
/poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/bcf.py
/poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/test_bcf.py
/poseidon/poseidonMonitor/NorthBoundControllerAbstraction/proxy/bcf/sample_state.py

**Comment by rashley-iqt** [comment]
Should this be a sub-element of the NorthBoundControllerAbstraction config?
like so
`[NorthBoundControllerAbstraction:Span_Fabric]`

**Comment by cglewis** [comment]
Yeah, that seems reasonable.

**Comment by rashley-iqt** [comment]
i'm actually rethinking this idea, because it seems like this only applies for the controller_type='bcf' at which point it seems like it would need to be under the `[NorthBoundControllerAbstraction:Update_Switch_State]` node.

**Comment by cglewis** [comment]
ah, yes that's true.

**Comment by cglewis** [comment]
@rashley-iqt looking at your test change for this, that makes sense since there's no longer the default of `None` for the span_name.  Though, since it's a variable, it might make more sense to be `%22SPAN_FABRIC%22` now instead of `%22vent%22`
