### ISSUE TITLE
configurations of rabbit server in poseidon.config

### ISSUE THREAD

**Issue by FahadMaqbool** [CyberReboot/poseidon#501]
how to set rabbit server address and port in poseidon.config
as I am getting this error (faucet and poseidon are on same PC)

**_# ERROR:pika.connection:Connection closed while authenticating indicating a probable authentication error
ERROR:pika.connection:Connection setup failed due to Client was disconnected at a connection stage indicating a probable authentication error: (403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.')
ERROR:pika.adapters.blocking_connection:Connection open failed - Client was disconnected at a connection stage indicating a probable authentication error: (403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.')
2018-02-23 07:13:51,009 - DEBUG - Rabbit_Base:64  - waiting for connection to 192.168.100.13 rabbitmq...
2018-02-23 07:13:51,009 - DEBUG - Rabbit_Base:65  - (403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.')_**

my configuration file is like this

**[Monitor]
config = True
logging_file = /tmp/poseidonWork/logging.json
logger_level = DEBUG
reinvestigation_frequency =  900
max_concurrent_reinvestigations = 2
scan_frequency = 5
rabbit_server = 192.168.100.13 #this is my PC's IP address 
rabbit_port = 5672
collector_nic = en0
collector_interval = 900
vent_ip = VENT_IP
vent_port = VENT_PORT
FA_RABBIT_ENABLED = True
FA_RABBIT_HOST = RABBIT_SERVER
FA_RABBIT_PORT = 5672
FA_RABBIT_EXCHANGE = 'topic_recs'
FA_RABBIT_EXCHANGE_TYPE = 'topic'
FA_RABBIT_ROUTING_KEY = 'FAUCET.Event'

[NorthBoundControllerAbstraction]
config = True

[NorthBoundControllerAbstraction:Handle_Resource]
config = True

[NorthBoundControllerAbstraction:Update_Switch_State]
config = True
controller_type = faucet
controller_uri = https://127.0.0.1:8443/api/v1/
controller_user = USERNAME
controller_pass = PASSWORD
controller_log_file = /var/log/ryu/faucet/faucet.log
controller_config_file = /etc/ryu/faucet/faucet.yaml
controller_mirror_ports = '{}'
rabbit_enabled = True

[Config]
config = True

[Config:Handle_FullConfig]
config = True

[Config:Handle_SectionConfig]
config = True

[Config:Handle_FieldConfig]
config = True

[NodeHistory]
config = True

[NodeHistory:Handle_Default]
config = True

[rest config test]
key1 = trident
key2 = theseus
double key = atlas horses**

**Comment by cglewis** [comment]
Are you running RabbitMQ on your machine already? For instance, if you run:
```
telnet 192.168.100.13 5672
```
does it connect or fail?

**Comment by FahadMaqbool** [comment]
Yes RabbitMQ is already running.
 telnet command connects.

**Comment by cglewis** [comment]
Is your RabbitMQ instance using any auth? Currently the configuration only supports a basic default guest auth.

**Comment by FahadMaqbool** [comment]
No. I haven't made any changing with rabbit MQ settings. Only user is 'guest' with password 'guest'

**Comment by cglewis** [comment]
that's odd. that should definitely work.  i'm not sure why that would throw that error, I'm unable to reproduce that myself.

**Comment by FahadMaqbool** [comment]
Okay, can you provide me configuration file that you are using.

**Comment by cglewis** [comment]
I don't change the default configuration directly, I set the appropriate environment variables per the `README` and use `./helpers/run` which handles modifying the configuration file to work with Poseidon when running on Vent.

**Comment by FahadMaqbool** [comment]
actually I have solved the error. I have removed the installations. then removed the rabbitmq server that was running already (May be that was the only problem). Then repeated all the steps to have a successful running system.
