### ISSUE TITLE
support L2 only learning and capture

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/poseidon#559]

**Comment by cglewis** [comment]
this now works for Faucet. BCF still need the API calls to be updated for it to work.

**Comment by gregs5** [comment]
Do you know what BCF calls need to be made and are waiting to implement, or would it be helpful if someone hunted down the correct API calls?  (And if so, what do they need to do, specifically?  Happy to help if I can...)

**Comment by cglewis** [comment]
I'm pretty sure the current API call is correct, the filter just needs to be updated from a `src-ip-cidr` to a `src-mac`.
