### ISSUE TITLE
Use case for using Poseidon in an IXP

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/poseidon#617]
Per #594, use case for using Poseidon in an IXP (Internet Exchange Point) setup.

@FahadMaqbool mentions the following use case: 

"
A very useful function to have in an IXP will be to have a detection and blocking mechanism of DDOS attack using advanced blackholing. http://conferences.sigcomm.org/sosr/2017/papers/sosr17-demo-blackholing.pdf
"

**Comment by FahadMaqbool** [comment]
Any plans to work on it soon? I am available for contributions.

**Comment by FahadMaqbool** [comment]
![ixp](https://user-images.githubusercontent.com/15454974/41893875-9ba0cfc8-7936-11e8-8cd0-43cd60978d66.PNG)

This kind of architectural design can be adopted.

**Comment by cglewis** [comment]
Hi @FahadMaqbool thanks for the diagram.  What does the SDX stack look like and how would that integrate with Poseidon?

**Comment by FahadMaqbool** [comment]
in an SDX, there will be some ISPs connected to each other using BGP peering through an SDN switch. similar to your setup, there will be an SDN controller (Faucet) to control the network. According to what I think is that the Poseidon should be running on the same system where Faucet is running and monitoring the traffic of a Peered ISP connected to SDN switch. for more details view this article for SDX stack, http://gtnoise.net/papers/2014/gupta-sigcomm2014.pdf

**Comment by cglewis** [comment]
Ah, ok. So if you're using Faucet as your SDN controller then it should be easy as hooking Poseidon up to it and setting the mirror ports you want per switch.  That takes care of the mechanics.  The harder part is the machine learning portion, which wouldn't know what to do with traffic coming from a scenario like that.  I would suggest trying to get Poseidon up and running on a network with Faucet and see how that works.  It will output garbage predictions from the machine learning part, but once you have that working, then I'd go to the PoseidonML repo (https://github.com/CyberReboot/PoseidonML) and fork that, train a new model using the data from your environment store that newly trained model with labels (pickle file and label_assignments.json) in your fork to replace the existing ones, then point Poseidon to your fork instead of the main repo in `.vent.startup.yml`

**Comment by cglewis** [comment]
closing as there hasn't been any new activity in over a year. please reopen if this is still of interest.
