### ISSUE TITLE
configured span_fabric / interface_group don't exist

### ISSUE THREAD

**Issue by rashley-iqt** [CyberReboot/poseidon#640]
with the changes being made for #399 and #400 it is possible for a user to configure poseidon to attempt to mirror using a combination of span fabric and destination interface group that aren't setup on the big switch controller.  in this case the call to 
`data/controller/applications/bcf/span-fabric[name=\"SPAN_FABRIC\"]`
or
`data/controller/applications/bcf/span-fabric[name=\"SPAN_FABRIC\"][dest-interface-group=\"INTERFACE_GROUP\"]`
will return an empty array that could cause errors to be thrown downstream.  We should at the very least log that an empty array is coming back, and possibly throw a more descriptive error.

**Comment by rashley-iqt** [comment]
@cglewis I'm implementing this error, i'm thinking either `LookupError` or `EnvironmentError` do you have a strong opinion one way or the other?

**Comment by cglewis** [comment]
`EnvironmentError`
