### ISSUE TITLE
Faucet controller_uri not being internally set when on the same host machine

### ISSUE THREAD

**Issue by scottkelso** [CyberReboot/poseidon#688]
### Description
When using the poseidon debian apt-get package, the controller_uri configuration variable doesn't seem to be set internally when faucet controller is running on the same machine as poseidon.  IE: controller_uri remains as None.

```
$ poseidon -c
# Generated from debconf - do not edit by hand, to change configuration options run: poseidon configure
#
#

controller_type=faucet
controller_uri=
controller_mirror_ports={"sw1":10}
FA_RABBIT_ENABLED=True
FA_RABBIT_HOST=RABBIT_SERVER
FA_RABBIT_PORT=5672
FA_RABBIT_EXCHANGE='topic_recs'
FA_RABBIT_EXCHANGE_TYPE='topic'
FA_RABBIT_ROUTING_KEY='FAUCET.Event'
collector_nic=s1-eth10
max_concurrent_reinvestigations=2
learn_public_addresses=No
logger_level=INFO
```

And then results in the following output...
```
poseidon[2471]: 2018-07-26T10:54:54+00:00 172.17.0.1 cyberreboot-poseidon-master/1adb2cb5143a/plugin[1960]: 2018-07-26 09:54:54,674 - INFO - EndpointWrapper:135 - None
poseidon[2471]: 2018-07-26T10:54:54+00:00 172.17.0.1 cyberreboot-poseidon-master/1adb2cb5143a/plugin[1960]: 2018-07-26 09:54:54,674 - INFO - EndpointWrapper:144 - ****************
poseidon[2471]: 2018-07-26T10:54:54+00:00 172.17.0.1 cyberreboot-poseidon-master/1adb2cb5143a/plugin[1960]: 2018-07-26 09:54:54,674 - INFO - EndpointWrapper:145 - ====STOP
poseidon[2471]: 2018-07-26T10:54:59+00:00 172.17.0.1 cyberreboot-poseidon-master/1adb2cb5143a/plugin[1960]: 2018-07-26 09:54:59,700 - ERROR - UpdateSwitchState:236 - Could not establish connection to None because 'NoneType' object has no attribute 'get_endpoints'.
poseidon[2471]: 2018-07-26T10:55:04+00:00 172.17.0.1 cyberreboot-poseidon-master/1adb2cb5143a/plugin[1960]: 2018-07-26 09:55:04,728 - ERROR - UpdateSwitchState:236 - Could not establish connection to None because 'NoneType' object has no attribute 'get_endpoints'.
poseidon[2471]: 2018-07-26T10:55:09+00:00 172.17.0.1 cyberreboot-poseidon-master/1adb2cb5143a/plugin[1960]: 2018-07-26 09:55:09,738 - ERROR - UpdateSwitchState:236 - Could not establish connection to None because 'NoneType' object has no attribute 'get_endpoints'.
```

### What Have I Tried?
- exporting the controller_uri set to my local ip address and then running `poseidon -r`
- setting the same var in /opt/poseidon/config/poseidon.conf and then running `poseidon -r`
- setting the same var in /opt/poseidon/.plugin_config and then running `poseidon -r`

None of the above changed the result.

This does not happen when using the exported env vars and `./helpers/run` to build

As a pedantic side note; the first string printed when running `poseidon -c` describes a command for changing the configuration as `poseidon configure`.  I think this should be `poseidon reconfig`.
```
$ poseidon configure
WARN: Unknown option (ignored): configure
```

### Environment
- Debian apt-get package
- Docker version 18.06.0-ce
- Ubuntu 18.04

### Steps to reproduce
- Install poseidon via https://github.com/CyberReboot/poseidon#installing
- In configuration, select `<YES>` when asked if Faucet controller is running on the same machine as poseidon 
- `poseidon -r` and see logs

**Comment by cglewis** [comment]
The `controller_uri` should be empty like that when Faucet is running on the same host, but it shouldn't be throwing that error.  Is Faucet running?

**Comment by cglewis** [comment]
Good catch on the configure/reconfigure note - fixing.  Thanks!

**Comment by scottkelso** [comment]
No, faucet is not running.  Should it be? I have always started my system in the following order...

1) poseidon
2) faucet, gauge, prometheus, grafana
3) mininet

I have also just tested there with faucet running before I start poseidon but I am still getting the same error.

I run faucet along with the other components like this...
```
# Run Faucet, Guage, Prometheus & Grafana-server
cd ~/workspace/faucet/
export FAUCET_EVENT_SOCK=1
export FAUCET_CONFIG_STAT_RELOAD=1
export FA_RABBIT_HOST=$ip
docker-compose -f docker-compose.yaml -f adapters/vendors/rabbitmq/docker-compose.yaml up --build -d
```

I also have faucet etc installed as services but I always check that they have been stopped. Otherwise the above docker-compose command would fail.

**Comment by cglewis** [comment]
Faucet should be running, yes.

One other thing I noticed, that might be causing this issue is you have:
```
controller_mirror_ports={"sw1":10}
```
and it should be:
```
controller_mirror_ports='{"sw1":10}'
```

**Comment by cglewis** [comment]
Actually, I'm also seeing this issue now - trying to track it down.

**Comment by cglewis** [comment]
I think I found the issue - sorry about that.  A `poseidon restart` should pick up the changes.  Let me know if that works.

**Comment by scottkelso** [comment]
Looks like that sorted it! Haven't come across the error at all today. Cheers!
