### ISSUE TITLE
Clean up logging

### ISSUE THREAD

**Issue by gregs5** [CyberReboot/poseidon#696]
The Poseidon logging was sufficient for our prototyping efforts, but I think it's time that we make the logging a bit more production-friendly.  Longer discussion, but off the top of my head we should minimally consider a few things:

1. Limit what goes to syslog to a smaller set of essential messages such as:
    a) Poseidon is started or stopped
    b) Critical errors Poseidon encounters while starting or running
    c) (maybe) Completed ML runs; it discovers / profiles a new node, the conclusion of that profiling. (e.g. 1.2.3.4 .67

2. Poseidon main loop information should be moved to a poseidon-specific log, IMO. I think seeing that it's spinning up a network capture, it has completed 15min of capture, it has completed the ML task, it has results, etc., is all good info and we should keep it - but I think we keep it out of the generic system log.  This way if one wants to do more advanced Poseidon debugging - GREAT! But it own't pollute the main system log.  (We should also think about replacing the '====START=====' like stuff with something more meaningful.  e.g. '==SDN Change: Configure Capture Port x')

3. Triplicate time/date stamps is overkill; let's not be `docker ps` with a 300 col shell window as a requirement to having your terminal not look like crap.  :)  syslog is going to do a time/date stamp which is sufficient for number 1, and we can do/time date for number 2.  But lets try to get rid of more than one time date stamp in a log entry.

Maybe we start with inventorying a list of log-worthy events?

**Comment by cglewis** [comment]
The third item has now been addressed, and only has one timestamp, also reduced some of the other parts to make the log shorter and cleaner.

**Comment by cglewis** [comment]
I've added another logger that will output to `/var/log/poseidon.log`  This will be for output about Poseidon's general runtime and things it's doing, learning, etc.  The original logger that gets sent to syslog will no longer have the informational or debugging logging, and will just have errors/warnings and generally whether poseidon is healthy/running/stopped/etc.

Here's the current counts of messages that get logged, I'll work on cleaning this up:
```
$ grep -ir "logger.debug" . | wc -l
     110
$ grep -ir "logger.info" . | wc -l
      10
$ grep -ir "logger.critical" . | wc -l
       0
$ grep -ir "logger.warning" . | wc -l
       9
$ grep -ir "logger.error" . | wc -l
      18
```

**Comment by cglewis** [comment]
ok, all of logging messages are now being routed to the correct loggers per suggestions 1 and 2 in the original issue.  the actual messages that are logged still need to be improved for readability/usefulness.
