### ISSUE TITLE
Poseidon Service doesn't stop

### ISSUE THREAD

**Issue by scottkelso** [CyberReboot/poseidon#706]
### Description
Poseidon doesn't stop when you stop it via poseidon debain apt-get package in terminal.

### Steps to Reproduce
Install using apt-get install [instructions](https://github.com/CyberReboot/poseidon#installing)
On boot, poseidon is running.  
Stop it with `poseidon -S` or `poseidon stop`.
Run `poseidon -i` or `poseidon info` and see that the service is still running.

I would have expected `poseidon stop` to have the same affect as `sudo systemctl stop poseidon.service`

### Environment
- Using apt-get install of poseidon
- Docker version 18.06.0-ce
- Ubuntu 16.04 and 18.04

**Comment by cglewis** [comment]
thanks for reporting this, I'll into it, as it should definitely be behaving like `sudo systemctl stop poseidon.service`
