### ISSUE TITLE
BigSwitch BCF Documentation not complete

### ISSUE THREAD

**Issue by gregs5** [CyberReboot/poseidon#709]
I will hopefully identify all the specifics in the next week, but given BCF minimally requires an account to be set up - and no mention of how to handle credentials - our current README probably isn't sufficient to get a BCF-based deployment up and running.  More to come...

**Comment by cglewis** [comment]
@gregs5 does #994 close this?

**Comment by gregs5** [comment]
Do we still want to maintain the read-the-docs page/site?

**Comment by cglewis** [comment]
the read-the-docs site needs a lot of work - i think we'd be better off going and finishing the gh-pages branch and using that.

**Comment by gregs5** [comment]
We can certainly do gh-pages!  If that's the case though, can we then nuke any poseidon references in read-the-docs? I want to try to avoid confusion for new folks with regard to docs being in multiple places. Fair?

**Comment by cglewis** [comment]
@gregs5 where do you see references to read-the-docs currently?

**Comment by gregs5** [comment]
Do they auto-gen that?

**Comment by cglewis** [comment]
but there's nothing from GitHub referencing that right? Just if you went to readthedocs you would find it?

**Comment by cglewis** [comment]
I deleted the readthedocs project, so that link no longer works.

**Comment by gregs5** [comment]
I think the current README covers us for BCF for now (my original concern). Going to close this.
