### ISSUE TITLE
Developing from a fork

### ISSUE THREAD

**Issue by rcaudill** [CyberReboot/poseidon#797]
From the README
```
If installed as described above, poseidon's codebase will be at /opt/poseidon. At this location, a .vent_startup.yml file can be edited to point to a fork of the original repository. Develop and commit changes on the poseidon fork and use poseidon -r to reload and see your changes.
```
I've edited .vent_startup.yml to point to my poseidon fork, made a simple change for testing, and run `poseidon -r` but my changes don't get applied. Am I missing something?

**Comment by cglewis** [comment]
That should work. What does your `.vent_startup.yml` look like and what change did you try to make?

**Comment by rcaudill** [comment]
```
$ cat /opt/poseidon/.vent_startup.yml
https://github.com/cyberreboot/vent:
    elasticsearch:
        build: no
        start: no
    file_drop:
        build: yes
        start: yes
    network_tap:
        build: yes
        start: yes
    rabbitmq:
        build: yes
        start: yes
    redis:
        build: yes
        start: yes
    rmq_es_connector:
        build: no
        start: no
    rq_dashboard:
        build: yes
        start: yes
    rq_worker:
        build: yes
        start: yes
        settings:
            instances: 4
    syslog:
        build: yes
        start: yes
https://github.com/rcaudill/poseidon:
    '@':
        build: yes
        start: yes
    api:
        build: yes
        start: yes
https://github.com/cyberreboot/vent-plugins:
    pcap_to_node_pcap:
        build: yes
    p0f:
        build: yes
    tcprewrite_dot1q:
        build: yes
https://github.com/cyberreboot/crviz:
    '@':
        build: yes
        start: yes
https://github.com/cyberreboot/poseidonml:
    onelayer:
        build: yes
vent.cfg:
    build-options:
        use_existing_images: yes
```

Really simple change to the help message: https://github.com/rcaudill/poseidon/commit/d9bf99d92934570c0cc734be10769833b19bb909

**Comment by cglewis** [comment]
Oh! The `bin/poseidon` won't get rebuilt against your fork, since it doesn't live in the container.  Only things inside of the `poseidon` directory inside of the repo will be changed using the above method, as that's what gets built inside the container.  For changes in the `/bin/poseidon` or other things outside of the `poseidon` subdirectory, you'll need to build a new `.deb` and reinstall.  That process hasn't been documented, but basically you run (it'll take a while, probably 30 minutes):
```
make build_installers
sudo dpkg -i dist/poseidon*.deb
```

**Comment by rcaudill** [comment]
Okay, that worked!
Would it be worthwhile for me to submit and PR to clarify/expand the Dev documentation in the README?

**Comment by cglewis** [comment]
Absolutely!
