### ISSUE TITLE
investigate if the need for interface-group for BCF is actually necessary if a span-fabric is already defined and dedicated to poseidon

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/poseidon#995]

**Comment by cglewis** [comment]
@gregs5 FYI

**Comment by rashley-iqt** [comment]
From reviewing the BCF web portal and testing the returns from their API it seems like a single span fabric can only reference a single interface group and a given interface group can only be referenced by a single active span fabric. This means we can assume that there is always a 1 to 1 relationship between the two constructs and, for purposes of retrieving span fabric info from the API, the two can be treated interchangeably. 
Reviewing the current code, a user should be able to specify either or both and have Poseidon work as intended with an error being logged if both values are configured but conflicting (i.e.: the designated interface group and span fabric exist but aren't linked). We should probably give some thought to how we want Poseidon to work in this scenario.
