### ISSUE TITLE
clean up filter rules for BCF on poseidon stop

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/poseidon#998]

**Comment by gregs5** [comment]
House cleaning: basically a "no filter" under span-fabric <name> should be issued to the controller before everything exits out; there shouldn't be any filter rules remaining once Poseidon shuts down.

**Comment by gregs5** [comment]
And I just tried doing it by hand - unfortunately you can't just "no filter" but instead you have to do the CLI equivalent of NO'ing the specific filter rule.  (e.g. `no 2 switch leaf01 interface ethernet20`) . Just wanted to clarify!

**Comment by gregs5** [comment]
...or (still learning!): `no <number>` (e.g. `no 2`)

**Comment by cglewis** [comment]
It will also now cleanup any stale rules on start in case the stop was not done gracefully. /cc @gregs5
